#!/usr/bin/env bash
# Title:        dns-speed.sh
# Author:       Luis Enrique Pineda @caniculari
# Description:  Test the DNS resolution time from several DNS servers

name="linux.org"
temp_file="/tmp/dns-speed.tmp"

# Create a temporary file to store the results
if [ -f $temp_file ]; then
  rm $temp_file
fi
touch $temp_file

# Test the dns servers listed on the dns-list.txt file
while read i; do
  sum=0
  for n_attempt in $(seq 1 3); do
    dns=`echo $i | awk -F ',' '{print $1}'`
    ip=`echo $i | awk -F ',' '{print $2}'`
    [ -z "$ip" ] && continue
    response=`dig +timeout=1 @$ip $name | grep 'Query time' | awk '{print $4}'`

    if [ -z "$response"  ]; then
      echo $dns $ip "not responding"
      break;
    else
      printf "%-20s %-20s %s ms\n" "$dns" "$ip" "$response"

      sum=$((sum + response))
    fi

    if [ "$n_attempt" -eq "3" ]; then
      printf "%-10s %-20s %s\n" "$((sum/3)) ms" "$ip" "$dns" >> $temp_file
    fi
  done
done < "$HOME/files/dns-list.txt"

# Print your fastest DNS
resolv="${1:-/etc/resolv.conf}"

printf "\n=== Write To $resolv ===\n"
fasred_ip="$(sort -g $temp_file | awk '{print $3}' | head -n 2 | xargs -I ip echo nameserver ip)"
printf  "%s\n%s\n" "$fasred_ip" "nameserver 8.8.8.8" | sudo tee $resolv

printf "\n=== DNS Speed Table ===\n"
sort -g $temp_file
rm $temp_file

